[package]
name = "commitment"
version = "0.2.3"
edition = "2021"
authors = ["Ryan Burmeister-Morrison"]
description = "Simplify your Git pre-commit hooks"
license = "GPL-3.0-or-later"
homepage = "https://github.com/rburmorrison/commitment"
repository = "https://github.com/rburmorrison/commitment"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5.60", features = ["derive"] }
crossterm = { version = "0.29.0", default-features = false, features = ["windows"] }
glob = "0.3.3"
indexmap = { version = "2.13.0", features = ["serde"] }
nom = "8.0.0"
serde = { version = "1.0.228", features = ["derive"] }

# deprecated, but we're using it for now until a good alternative is found
serde_yaml = "0.9.34"
